
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ngosi
 */
public class GIAODIEN extends javax.swing.JFrame {

    /**
     * Creates new form GIAODIEN
     */
    static int dem=0;
    static DefaultTableModel dtm;
    private Vector vt = null;
    private ArrayList<CAUHOI> listWh;
    private DSDAPAN listAns;
    
    public GIAODIEN() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); 
        listWh = new ArrayList<>();
        listWh = new DSCAUHOI().docFileWh();
        listAns = new DSDAPAN();
        listAns.docFileAns();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DAPAN = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbcauhoi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        btnShowAns = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbView = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLamBai = new javax.swing.JButton();
        btnNopBai = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        lbPos = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbuser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CHƯƠNG TRÌNH THI TRẮC NGHIỆM");
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbcauhoi.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbcauhoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbcauhoi, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Câu Hỏi");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ĐÁP ÁN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 51, 51))); // NOI18N

        DAPAN.add(A);
        A.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        A.setEnabled(false);
        B.setEnabled(false);
        C.setEnabled(false);
        D.setEnabled(false);

        DAPAN.add(B);
        B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        DAPAN.add(C);
        C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        DAPAN.add(D);
        D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        btnShowAns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnShowAns.setForeground(new java.awt.Color(51, 153, 255));
        btnShowAns.setText("Hiển Thị Kết Quả");
        btnShowAns.setActionCommand("");
        btnShowAns.setAutoscrolls(true);
        btnShowAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAnsActionPerformed(evt);
            }
        });
        btnShowAns.setEnabled(false);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbView.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbView.setForeground(new java.awt.Color(51, 153, 255));
        tbView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÂU", "ĐÁP ÁN CHỌN", "ĐÁP ÁN ĐÚNG"
            }
        ));
        jScrollPane2.setViewportView(tbView);
        tbView.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnShowAns, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnShowAns, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnLamBai.setBackground(new java.awt.Color(0, 153, 255));
        btnLamBai.setForeground(new java.awt.Color(255, 255, 255));
        btnLamBai.setText("LÀM BÀI");
        btnLamBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamBaiActionPerformed(evt);
            }
        });
        jPanel3.add(btnLamBai);

        btnNopBai.setText("NỘP BÀI");
        btnNopBai.setEnabled(false);
        btnNopBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopBaiActionPerformed(evt);
            }
        });
        jPanel3.add(btnNopBai);

        btnExit.setText("THOÁT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnPrev.setText("TRỞ VỀ");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrev);

        lbPos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbPos);

        btnNext.setText("QUA CÂU");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel5.add(btnNext);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        lbuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(lbuser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
     
    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        listWh.get(dem).setDapAnUser(D);
    }//GEN-LAST:event_DActionPerformed

    private void btnLamBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamBaiActionPerformed
      dem = -1;
      String user = JOptionPane.showInputDialog("HOTEN_MSSV");
        lbuser.setText(user);
         if(user.isEmpty()){
         this.dispose();
        }
      btnLamBai.setEnabled(false);
      btnPrev.setEnabled(true);
      btnNext.setEnabled(true);
      btnNopBai.setEnabled(true);
      btnShowAns.setEnabled(true);
      A.setEnabled(true);
      B.setEnabled(true);
      C.setEnabled(true);
      D.setEnabled(true);
      this.btnNextActionPerformed(evt);
    }//GEN-LAST:event_btnLamBaiActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        dem--;
        if(dem == -1) dem = 19;
        int count = dem + 1;
        lbPos.setText(String.valueOf(count) +"/20");
        String cauhoi = listWh.get(dem).getCauhoi();
        String dapAnA = listWh.get(dem).getDapAn1();
        String dapAnB = listWh.get(dem).getDapAn2();
        String dapAnC = listWh.get(dem).getDapAn3();
        String dapAnD = listWh.get(dem).getDapAn4();
        lbcauhoi.setText(cauhoi);
        A.setText(dapAnA);
        B.setText(dapAnB);
        C.setText(dapAnC);
        D.setText(dapAnD);
        DAPAN.setSelected(listWh.get(dem).getDapAnUser().getModel(), rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnPrevActionPerformed
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        dem++;
        if(dem==20) dem =0;
        int count = dem + 1;
        lbPos.setText(String.valueOf(count) +"/20");
        String cauhoi = listWh.get(dem).getCauhoi();
        String dapAnA = listWh.get(dem).getDapAn1();
        String dapAnB = listWh.get(dem).getDapAn2();
        String dapAnC = listWh.get(dem).getDapAn3();
        String dapAnD = listWh.get(dem).getDapAn4();
        lbcauhoi.setText(cauhoi);
        A.setText(dapAnA);
        B.setText(dapAnB);
        C.setText(dapAnC);
        D.setText(dapAnD);
        DAPAN.setSelected(listWh.get(dem).getDapAnUser().getModel(), rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnNextActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        listWh.get(dem).setDapAnUser(A);
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
         listWh.get(dem).setDapAnUser(B);
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
         listWh.get(dem).setDapAnUser(C);
    }//GEN-LAST:event_CActionPerformed

    private float sumPoint(){
        float point = 1.0f;
        final float hesoPoint = 0.5f;
        int pos=0; 
        try {
        int length = listWh.size();
        char dapAnUser;
        char dapAnDung;
        dtm = (DefaultTableModel) tbView.getModel();
        
            for(int i=0;i<length;i++){
                  pos = listAns.Search(listWh.get(i).getId_wh());
                if(pos != -1) {
                    dapAnUser = listWh.get(i).getDapAnUser().getText().charAt(0);
                    dapAnDung = listAns.getListDapAn().get(pos).getDapAnDung().charAt(0);
                    if(dapAnUser == dapAnDung) {
                       point += hesoPoint;
                    }else {
                       vt = new Vector();
                       vt.add(i+1);
                       vt.add(dapAnUser);
                       vt.add(dapAnDung);
                       dtm.addRow(vt);
                    }
                }
            }
            if(vt.size() > 0) tbView.setModel(dtm);
            
        } catch (NullPointerException | StringIndexOutOfBoundsException ex1) {
        }
        return point-1.0f;
    }
    private void btnNopBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopBaiActionPerformed
            float diem = sumPoint();
              JOptionPane.showMessageDialog(rootPane,  "Số Điểm Của Bạn Là: "+diem+"");
              int check = JOptionPane.showConfirmDialog(rootPane, "THI LAI");
              if(check == JOptionPane.YES_OPTION) {
                  this.dispose();
                  java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                  new GIAODIEN().setVisible(true);   
            }
        });
              }
    }//GEN-LAST:event_btnNopBaiActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnShowAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAnsActionPerformed
        int pos = listAns.Search(listWh.get(dem).getId_wh());
        char dapAnDung = listAns.getListDapAn().get(pos).getDapAnDung().charAt(0);
        dtm = (DefaultTableModel) tbView.getModel();
        try {
             vt = new Vector();
             vt.add(dem+1);
             vt.add("");
             vt.add(dapAnDung);
             dtm.addRow(vt);
             tbView.setModel(dtm);
        } catch (NullPointerException e) {
        }
        
        
    }//GEN-LAST:event_btnShowAnsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
           
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIAODIEN().setVisible(true);
               
            }
        });
       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.ButtonGroup DAPAN;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLamBai;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNopBai;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnShowAns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbPos;
    private javax.swing.JLabel lbcauhoi;
    private javax.swing.JLabel lbuser;
    private javax.swing.JTable tbView;
    // End of variables declaration//GEN-END:variables
}
